### ISSUE TITLE
Unable to receive assertion

### ISSUE THREAD

**Issue by timnewham** [davelester/WPBadger#21]
Hi, I've just installed the latest version of WPBadger on a totally fresh WP3.4.1 site (twenty twelve theme) on my own cloud server. Badge appears here: http://31.222.165.94/wordpress/?badge=openbadge101 (should I see a "featured image"? I've uploaded a png to the post).

I can go through the process of awarding a badge.

When a learner goes to accept the badge (from http://31.222.165.94/wordpress/?award=282091916585341#), they get an error:

We have encountered the following problem: trying to grab url http://31.222.165.94/wordpress/?award=185326276021078&json=1 got error ParseError: Failed to parse JSON at http://31.222.165.94/wordpress/?award=185326276021078&json=1: Unexpected token

Can anyone help? I'm only quasi-technical (know enough to download and install wordpress and edit config files, but don't know enough to debug or write code)

Thanks!

Tim Newham
tim@think-associates.co.uk

**Comment by davelester** [comment]
Two things about your badge description:
1. There's no need to include HTML in the description, including linking to an external file.
2. I tested your assertion file, and the Open Badges Infrastructure enforces a limit of 128 characters for badge descriptions. Try reducing the length of your description and see if you experience the same error. I've also added this as a ticket on github, Issue #22. 

Dave

**Comment by timnewham** [comment]
Thank you Dave.

I've now created a new test badge here with minimal information/characters (it's just called "A" with no other information): http://31.222.165.94/wordpress/?badge=a

And I now get, on award: http://31.222.165.94/wordpress/?award=784077297709882

"We have encountered the following problem: badge assertion appears to be invalid".

(if this is getting into more "user support" than "bug fixing, do let me know :) )

Tim

PS: As an aside, I'd assumed that the OBI would allow me lots of text, html etc to describe a badge, so that the issuer could record: a) the assessment criteria for a badge and (b) when awarding, the evidence that the learner has submitted to achieve the badge. But I guess that's a question I should pose over at the OpenBadges community...

**Comment by davelester** [comment]
Can you do me a favor and update your badge version to 1.0, instead of 1? The OBI specifies the format of badge numbers, which need to be x.x, or x.x.x. I hope to add a notification about this in an upcoming release, WPBadger 0.8, and have made this part of the todo for Issue #3.

**Comment by timnewham** [comment]
Done (and awarded to wpbadger@noreply.github.com at http://31.222.165.94/wordpress/?award=538730179984122)

Tim Newham
Think Associates Ltd
07887 923032

-----Original Message-----

**Comment by davelester** [comment]
Great. Two additional things:
1. Add a description for the badge. It should be between 1 and 128 characters long.
2. Update the email address you've awarded the badge to. It should be the same as your mozilla persona

Once you've done this, can you try accepting the badge and let me know how it goes?

**Comment by timnewham** [comment]
Yes! That all works now, thank you very much Dave. So to summarise:

Version must be x.x or x.x.x format
Description must exist and be between 1 and 128 characters. If in doubt, don't include html in description.

Proof (no need to look, just posting here because I'm proud....) http://beta.openbadges.org/share/0dee7de1891f3a06f1bdbef25c3ac0f3
