### ISSUE TITLE
Provide fallbacks for values required by OBI JSON validator

### ISSUE THREAD

**Issue by boonebgorges** [davelester/WPBadger#35]
There are some values that are required by the OBI spec, but in some circumstances are not being properly set on my setup: `version` and `badge.image` are the two I've run into. It would be nice to provide fallbacks for these values (in the form of wrapper functions, I guess) so that badges erroneously created without these values can still be correctly awarded.

In the case of images, this would also probably mean providing a default badge image.

An alternative to this technique is to disable Awards associated with a given Badge if we've determined that the Badge assertion won't pass validation.

See also #3 on badge info validation, and #17 on miscellaneous errors.

**Comment by davelester** [comment]
In a recent commit, @sbutler shared a patch that accomplishes your alternative. For the most part, badge images should be original so I'm hesitant to provide a fallback image. Where I've seen people get lost is specifying a version, but as I brought up in issue #45 the current implementation of version is actually a misreading of the OBI spec. I'm learning toward removing the version entirely -- please follow-up in the other issue if you have questions or concerns.
