### ISSUE TITLE
Accepting Badge gets Unreachable error ?

### ISSUE THREAD

**Issue by adamprocter** [davelester/WPBadger#36]
We have encountered the following problem: trying to grab url http://myblog.com/rcs/awards/429906602995470/?json=1 got error UnreachableError: Unable to retrieve assertion from the following url: http://myblog.com/rcs/awards/429906602995470/?json=1

My wordpress is part of multi worpress install and currently only allows connections from specific sites 

Can you advise what URLS I should allow connections from ? (if you think this will help)

**Comment by adamprocter** [comment]
Any clues ?

**Comment by davelester** [comment]
Does the award still exist? The url without the /?json=1 should be valid; since it's currently a 404 error, I would assume that there's a problem in the rewrite rules. Can you confirm that the award is "published"?

**Comment by adamprocter** [comment]
Yes its published

**Comment by davelester** [comment]
Can you share the actual URL so I can take a closer look at the actual assertion file? If you would like for this to be private, feel free to drop me a line: dave@ischool.berkeley.edu

**Comment by adamprocter** [comment]
the URL is blocked to a specific IP range so I cant. but they have now added an exception for mozilla.net and I get this error ?  I can email you the URL if that is of any use ?

We have encountered the following problem: badge assertion appears to be invalid

**Comment by davelester** [comment]
Definitely, feel free to email the URL or even just copy/paste the contents of the JSON assertion file and I can help check what's going on. You can also copy-paste your assertion into the openbadges validator and see what's up: http://beta.openbadges.org/issuer/validator 

If the assertion file is invalid, the most common problems are related to data entry, including:
- badge version numbers must be x.x, or x.x.x, like 1.0 or 1.0.0
- if your badge or award description includes quotations, it may not be properly escaped in the JSON file. (that's a bug)
- there is a limit in the openbadges spec for how long the badge criteria can be -- if that's exceeded, then you'll run into issues. I created [issue #230](https://github.com/mozilla/openbadges/issues/230) about this, but haven't heard back
- newlines in your badge description may also be breaking your assertion. see [issue #256](https://github.com/mozilla/openbadges/issues/256)

I'm also not 100% sure what IP addresses you would need to add an exception for in order for Mozilla to access your assertion file. If it's an error related to accepting a badge into one's backpack, I would guess that host would be beta.openbadges.org, but you may want to confirm by asking on the openbadges IRC channel: #badges on irc.mozilla.org

**Comment by adamprocter** [comment]
have emailed you some details

**Comment by adamprocter** [comment]
Its a known Firewall bug https://github.com/mozilla/openbadges/issues/402 - have been asked to put in my use case.

**Comment by adamprocter** [comment]
To note I was missing some info from the json assertion stuff stuff that means I am now getting the following error -

 "We have encountered the following problem: trying to grab image at url http://myblog.soton.ac.uk/blog/files/2012/10/walk.png got error UnreachableError: Unable to retrieve image from the following url: http://myblog.soton.ac.uk/blog/files/2012/10/walk.png"

**Comment by adamprocter** [comment]
Ok removing the featured image gives me the error - i guess it messed up the jSON file..

"badge assertion appears to be invalid"

 I cant use a URL to an image as there is no option to set as featured (server to dish up badge image)

**Comment by davelester** [comment]
When the plugin is installed, it should fail and alert the user if their theme doesn't support-thumbnails (which add the "set as featured image" link).

Try adding the following line to your current theme's functions.php file:

`add_theme_support( 'post-thumbnails' );`

**Comment by adamprocter** [comment]
Ok however for you info the set as featured link is is ok on the from media tab but not the option us not there for from URL tab. 

Adam

**Comment by davelester** [comment]
There should be three tabs in the set featured image popup window: from computer, from url, or media library. Sounds like you want to use "from url."

**Comment by adamprocter** [comment]
Yes that option is only present on media library tab / or after from Computer uploads
No option on from URL appears or is present.

(attached)

**Comment by davelester** [comment]
btw, the attachment doesn't send through github. It sounds like your problem is similar to this: http://answers.yahoo.com/question/index?qid=20110116231520AAZwrnh. Maybe a theme issue?

**Comment by adamprocter** [comment]
I'm just using the default 2012 theme :( ill ask our IT people to look into this though. 

Thanks for all your help
Adam

**Comment by kevinmulryne** [comment]
Hi - I'm having the same problem. I can preview the badge fine until I publish it - then it just returns a page not found. When I try and collect the award it gives a similar error to the above - i.e. it can't issue a badge which doesn't exist...

**Comment by chriswilde** [comment]
Hi, I'm getting this error message too...I've had a play and installed a couple of different themes, but this has had no effect. Everything works fine...I can create the badge, and send it to the mail address no problem, but when the user follows the link to add the badge to the backpack i get the following error:

We have encountered the following problem: trying to grab url http://www.wildmelonhistory.com/openbadges/?award=888839413458481&json=1 got error ParseError: Failed to parse JSON at http://www.wildmelonhistory.com/openbadges/?award=888839413458481&json=1: Unexpected token '

Could you advise please Dave? This is an excellent tool and idea, and I'm looking to test it in a school in January...

**Comment by kevinmulryne** [comment]
Hi Chris. I have got mine working now. Here are the things I did - just in case any of these help (Dave told me to check all these...):
1. I did a completely new installation of WordPress with no plugins and with the default theme
2. I made sure the badge version was 1.0 rather than 1
3. I made sure the badge description had no markup in it - i.e. only plain text
4. I made sure the badge description only had a few words in it

I'm happy to issue you a badge with my set up if it would help or have a look at your set up - but Dave is the technical guy, obviously.

Kevin :)

**Comment by kevinmulryne** [comment]
Also, Chris, I would be interested in following your progress as I am setting up a trial of Open Badges at the National College and would love to share experiences with you.

Thanks,

Kevin

**Comment by adamprocter** [comment]
Working for me
In the end I had to ensure all the admin settings where correct
Dashboard > Settings > WPBadger
As my WP is behind a firewall I also had to white list mozilla.net and the media folder so that the featured images could be sent.

**Comment by chriswilde** [comment]
Hi Guys,
thanks for the support and ideas...I'm getting closer!!!
No longer getting the error message...think this was due to an apostrophe in my settings details.
I'm now getting the following message:
We have encountered the following problem: badge assertion appears to be invalid
I'm getting closer though, and have some time tonight to review the server side stuff, and try outside of our firewall.
Fingers crossed we'll be up and running by mid evening.
Thanks again,
Chris

**Comment by chriswilde** [comment]
Gents....Its working!!
Brought it down then re-installed and have issued a test badge!!!!!
Thanks so much for the excellent system, and support network.

**Comment by kevinmulryne** [comment]
Hooray! Why not make a celebration badge and issue it to us!! (Joke.) Glad it worked out in the end. :)

**Comment by davelester** [comment]
Terrific! Congrats on successfully issuing badges. If you'd like to add yourself to the [list of people or organizations using WPBadger](https://github.com/davelester/WPBadger/wiki), I'd appreciate it!
