### ISSUE TITLE
Badges not found

### ISSUE THREAD

**Issue by kevinmulryne** [davelester/WPBadger#41]
When I create a badge and then try to view badge it just says Page not found. 

When I try to claim it, everything works except I get:

We have encountered the following problem: trying to grab url http://www.mulryne.com/awards/403833486186340/?json=1 got error ParseError: Failed to parse JSON at http://www.mulryne.com/awards/403833486186340/?json=1: Unexpected token h

**Comment by davelester** [comment]
Your badge description shouldn't include markup. Try adding a short one and seeing if that fixes the problem.

Also, I noticed that your site is running drupal -- where is your WordPress install located? It's possible that the url rewriting is not working properly as a result of a customization.

**Comment by kevinmulryne** [comment]
Thanks Dave. Yes I saw the Drupal thing - I've no idea why that is there. I'll try the no markup thing and also I think I will do a clean installation of WordPress just for badges so I can make sure there is nothing which could be conflicting!

I'll let you know how it goes.

**Comment by kevinmulryne** [comment]
Well, I did a clean installation and all looked good. The badge page exists after publishing and looks fine. However, when trying to accept the badge I created I now get a different error - "We have encountered the following problem: badge assertion appears to be invalid". One step forward though...

The badge I have created is here - http://www.mulryne.com/cleanbadges/?badge=ymp-listener

**Comment by davelester** [comment]
Can you share the link to an awarded badge? That will allow me to look at your assertion file and see what else is going on.

**Comment by kevinmulryne** [comment]
Hi Dave. I assume this is what you mean - http://www.mulryne.com/cleanbadges/?award=925378176243975 
Thanks for your help! I'd love to get this working so I can start issuing my own badges and not rely on badg.us!

Kevin

**Comment by davelester** [comment]
Thanks. I ran your [assertion file](http://www.mulryne.com/cleanbadges/?award=925378176243975&json=1) through the [Open Badges validator](http://beta.openbadges.org/issuer/validator) and it looks like the problem is that your badge version is 1 instead of 1.0. Try updating it and seeing if it works.

There's a [recent commit](https://github.com/davelester/WPBadger/commit/a19eb8c76f7b966106a9452a8d04d0f643e224f7) to WPBadger that forces badge versions into this format, but I haven't released it officially since there are several other open tickets related to validation.

**Comment by kevinmulryne** [comment]
Same result with 1.0 I'm afraid...

**Comment by davelester** [comment]
Can you double-check that you've saved the badge version? I checked your assertion, and it still says your version is 1. This may be a caching issue.

**Comment by kevinmulryne** [comment]
Aha! I actually just tried a new one _and it worked!!_ Fantastic and thanks for your help! I can now call myself an official open badge issuer in my own right! Badg.us is great but so much more satisfying to use your own WordPress installation!!

Many thanks again. Very excited (as you can probably tell!)

**Comment by davelester** [comment]
Terrific! If you wouldn't mind, please also add your website and/or organization to the WPBadger wiki [https://github.com/davelester/WPBadger/wiki](https://github.com/davelester/WPBadger/wiki), where I'm keeping a list of who is using WPBadger.
