### ISSUE TITLE
JSON error trying to post to Open Badge Backpack

### ISSUE THREAD

**Issue by johnnsb** [davelester/WPBadger#44]
I just set up a new WP instance, running off dyndns for now, and (gratefully and humbly) stumbed on your plugin. Set up a badge, added one award, sent email. When user chooses to accept the award, and goes to their Open Badge Backpack, they get the following error:

![badge_error](https://f.cloud.github.com/assets/1466535/23653/9708b8ee-4a58-11e2-8184-a7fdbc3509b5.png)

Only tested on Chrome so far.

John

**Comment by davelester** [comment]
I followed the [link included in the screenshot](http://jpshome.dyndns-office.com:8888/wordpress/awards/940920031862333/?json=1), and it appears that the award has since been deleted or made private. What I usually do during similar instances is first eyeball the json file that the plugin generates to see if any anomalies stand out, and I also run the file through the [Open Badges validator](http://beta.openbadges.org/issuer/validator) to identify what is making the assertion invalid.

Could you create a new award and share the link here, or try validating the assertion file yourself? We should be able to get to the bottom of the issue.

**Comment by jamesmichie** [comment]
I am also having the same problem, running the Twenty Eleven theme. Image attached.

![WPBadger JSON Error](https://f.cloud.github.com/assets/3209267/48295/91f3a466-5905-11e2-835c-9a45264033ee.png)

**Comment by davelester** [comment]
James,

In the case of your award, it looks like you've included HTML in your badge description. Try updating the description to be 128 characters or less, without HTML.

**Comment by jamesmichie** [comment]
Does the badge description count as the 'meta-data'? If not how do I edit the meta-data?

And thanks for your speedy response by the way. :-)  

---

James Michie  

@jamesmichie (http://twitter.com/jamesmichie)  

http://jamesmichie.com (http://jamesmichie.com/)

**Comment by jamesmichie** [comment]
Edited badge description. Still having same issue.

**Comment by davelester** [comment]
@jamesmichie: can you share the award url? I'll take a closer look at its JSON assertion file.

**Comment by jamesmichie** [comment]
http://jamesmichie.com/criticalskills/awards/702621670998632

**Comment by davelester** [comment]
Very minor, but it looks like there's a newline following your badge description that's making the assertion file invalid. Try removing that, and it should work.

**Comment by jamesmichie** [comment]
Brilliant! Sorted.  

Is there a way to display the badge itself on the badge page?

At the moment I get this, even though I have set the featured image: http://jamesmichie.com/criticalskills/badges/research-and-enquiry/

And thanks for the help, much appreciated. :-)  

---

James Michie  

@jamesmichie (http://twitter.com/jamesmichie)  

http://jamesmichie.com (http://jamesmichie.com/)

**Comment by davelester** [comment]
Not yet, but there's a ticket already online to add this in the future, #38.

**Comment by jamesmichie** [comment]
Okay, that's great.  

Thanks for all your help. I added myself to the list of people using WPBadger. :-)  

---

James Michie  

@jamesmichie (http://twitter.com/jamesmichie)  

http://jamesmichie.com (http://jamesmichie.com/)

**Comment by davelester** [comment]
This JSON error occurs for a variety of reasons related to incorrect inputs.

I'm closing this ticket, since this will continue to be improved and prevented with future commits to add validation to badges and awards.
