### ISSUE TITLE
Page not found - Badge does not publish

### ISSUE THREAD

**Issue by joerglohrer** [davelester/WPBadger#53]
I can create Badges and as long as they are drafts, they can be viewed.
But as soon as ich publish them, they can not be reached anymore.
Neither by preview nor by view - 
Page not found: 
http://www.elektrisches-lernen.de/badges/noch-ein-badge/

So the awards can be given and accepted but not backpacked: "We have encountered the following problem: Invalid assertion structure":
http://www.elektrisches-lernen.de/awards/587291082600131/

**Comment by davelester** [comment]
You can access the assertion file that WPBadger generates by adding json/ to the url, so in your case that's http://www.elektrisches-lernen.de/awards/587291082600131/json/

Looking at this JSON file, a few problems jump out at me. You must add a Name, Description, and Criteria for your badge. Additionally, your badge must have an image and a version number in the format of 1.0 or 1.0.0.

**Comment by edventures** [comment]
I'm in a similar spot - I've created the award but the user only receives an email without the accept/decline link. In my WP install, I cannot view the award when it is listed as published but can view it when it is listed as a draft. When I click the link in the draft preview, the lightbox works and I can log into my account but then the backpack returns the following error: "We have encountered the following problem: Tried to get undefined file at undefined and got an HTTP undefined"

**Comment by edventures** [comment]
Ok, so I changed my Permalink option from postname to default, and then set the Award back to Published, and it worked! Not sure why that made a difference but you'll probably get more feedback from folks who prefer customized  post URL Dave. Now to retest the user interface when awarding badges to users to see if it changes the mail message they receive so that they know how to handle their newly earned badge.

**Comment by davelester** [comment]
@edventures and @empeiria: what version of WordPress are you each using? I wonder if there's a version incompatibility at work here that's causing these issues.

**Comment by edventures** [comment]
I'm on the latest version I believe 3.5.1

On Wed, May 29, 2013 at 3:14 PM, Dave Lester notifications@github.comwrote:

> @edventures https://github.com/edventures and @empeiriahttps://github.com/empeiria:
> what version of WordPress are you each using? I wonder if there's a version
> incompatibility at work here that's causing these issues.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/davelester/WPBadger/issues/53#issuecomment-18639409
> .

## 

_John Martin_
johnericmartin.com
_603.254.6954_
_Skype_: edventures
_Twitter:_ edventures

**Comment by joerglohrer** [comment]
I have 3.5.1 and I played around a little, too. So first i changed the Permalinks to default and the Format "1.2.3" and it worked -  then I changed back the Permalink to name and it still works. So i don't touch the running system ;-) Seemed to be the Problem with the version number of the badge "1" instead of "1.0" 
Thank you very much
Where can I customize the mail-topic "Congratulations! You have been awarded ... badge!" and the text of the Award: "Please choose to accept badge or decline badge" ? Because i want to translate this into german!

**Comment by davelester** [comment]
@empeiria I created a ticket to add support for Internalization #57. In the meantime, you'll have to manually edit any english strings in the codebase (sorry!)

I'm closing this issue since it appears @empeiria was able to resolve the issue. Feel free to reopen it if the problem persists.
