### ISSUE TITLE
Get award page but no lightbox connection to OpenBadges when clicking the link to accept

### ISSUE THREAD

**Issue by edventures** [davelester/WPBadger#54]
URL: http://jemartin.com/

Downloaded and installed version 0.6.2 of the WP Badger plugin. 
Created a badge, then awarded myself the badge to test the process. 
Received the award email, clicked the link and the award page loads with accept/decline links however clicking on either link does nothing. 
Tried perusing the various support links but couldn't find anything recent that replicated my results as most issues were for prior versions of the plugin.

**Comment by edventures** [comment]
UPDATE: Realized that your development version was newer than the one in WP Plugins. Installed your code and tweaked my badges. Now, when the user receives the email, there is no link to accept/decline, just the content of the message sent to them in the post content field.

**Comment by davelester** [comment]
To clarify: are you having this problem on the github version or what's on wordpress.org?

**Comment by davelester** [comment]
actually, it appears that another user had this same issue. Please follow this new ticket: https://github.com/davelester/WPBadger/issues/55
