### ISSUE TITLE
Award e-mail not including accept/decline link

### ISSUE THREAD

**Issue by jacobmollstam** [davelester/WPBadger#65]
Hi!
First of all: Thanks for a great tool. I attended a seminar on Open Badges like 9 months ago and was hooked immediately and have since then been reading about it. my coding skills are not what they should be but I'm experienced with Wordpress so this is great. 

I followed your detailed instructions for setting up and think I got everything right but when I test it out by awarding myself a badge I get the confirmation letter, but completely without a link to accept or decline. Hence it doesn't show up in my backpack and thus not in my embedded thingy on the wordpress site. 

Any ideas of what I might be doing wrong?

Have a great day!
//jacob

**Comment by davelester** [comment]
I'll plan to investigate this over the weekend. Can you let me know which version of WordPress you're using?

**Comment by jacobmollstam** [comment]
Thanks. I'm running the latest 3.8 update.
//Jacob

**Comment by davelester** [comment]
Howdy, I just installed a fresh copy of 3.8 (using code from GitHub -- I'm not sure if that is in sync with what's on the WordPress plugins site) and was unable replicate this specific issue on my first try.

To clarify how the confirmation emails are supposed to work: upon awarding a badge an email is sent to the user that includes a link to the award page. It's on that page that the user can accept or decline a badge. There is not normally an accept or decline link included directly in the email itself (although perhaps there should be)..

Let's keep debugging this. Did you create an email template on the WPBadger config page, and possibly forget to include the {BADGE_URL}? And if so, if you remove a custom template and WPBadger uses its default template do you still run into this issue?

**Comment by jacobmollstam** [comment]
Hi Dave. 
Thanks for your help! When I use the original message it works. But here's the weird part: When I use the  {BADGE_URL} code in my custom message it doesn't work. I've traced it back to the fact that when I create the badge itself it creates a bad URL. I get a typical Error 404 message stating that the page doesn't exist. Do you anything about what might be wrong? Is there a required form for the perma links that I forgot to set?

Also, I have a general question that might involve the WP Badger and it might not. I'm not sure. Is there a way to push new badges to a given collection? Or would it be a future development of your widget that maybe allows learners to decide directly from their accept/deny page?

I'm trying to set up a useful infrastructure for my students who are both quite young (K-5) and mostly non english speakers. The task of logging on to the Open Badges Backpack and manually doing it that way would be too hard for them...

**Comment by davelester** [comment]
Have you "published" the badge and the award, or are they saved as drafts? Also, are pages on the WordPress blog accessible, or are they also inaccessible? The awarded badge should be accessible whether or not you have turned permalinks on.

In terms of pushing badges to a given collection, I don't believe that's part of the open badges specification (and not something WPBadger currently supports). I would suggest posting the suggestion  to the [Open Badges mailing list](https://groups.google.com/forum/#!forum/openbadges).

**Comment by jacobmollstam** [comment]
Yeah, now it seems to be working fine. 
The link in the e-mail to the actual award works and after a while the badge itself is accessible too.
Once again thank you for helping me out. I've spent some time researching other options and well... the WP Badger and the WP Badge Display are by far the best ones. 

I'm gonna head over to the mailing list to suggest my idea of pushing badges to given collections. 
Take care.
